version: '3.7'

services:
  roguelike:
    container_name: roguelike
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - PUBLIC_URL=/
