export enum RunState {
  PRERUN = 'PRERUN',
  WAITING_INPUT = 'WAITING_INPUT',
  PLAYER_TURN = 'PLAYER_TURN',
  WORLD_TURN = 'WORLD_TURN',
  GUI_INVENTORY = 'GUI_INVENTORY',
  GUI_INVENTORY_DROP = 'GUI_INVENTORY_DROP',
}
